---
- name: Prepare
  hosts:
    - controller
    - copter
  tasks:
    - name: upload dummy sololink_config
      template:
        src: "sololink_config"
        dest: "/bin/sololink_config"
        mode: 0770
