---
- name: Download {{ iMX_file }}
  block:
    - name: tar
      get_url:
        url: "{{ _iMX_tar_URI }}"
        dest: "{{ tmp }}/{{ _iMX_tar }}"
        force: no
      delegate_to: localhost

    - name: md5
      get_url:
        url: "{{ _iMX_md5_URI }}"
        dest: "{{ tmp }}/{{ _iMX_md5 }}"
        force: no
      delegate_to: localhost

  become: false
  register: result
  until: result is success
  retries: 3
  delay: 2

# TODO: ensure sololink_config exists

- name: update-prepare
  command: "sololink_config --update-prepare sololink"

- name: copy {{ iMX_file }}
  block:
    - name: tar
      copy:
        src: "{{ tmp }}/{{ iMX_tar }}"
        dest: "/log/updates/{{ iMX_tar }}"
        mode: 0660

    - name: md5
      copy:
        src: "{{ tmp }}/{{ iMX_md5 }}"
        dest: "/log/updates/{{ iMX_md5 }}"
        mode: 0660

  force: yes

- name: update-apply
  # command: "sololink_config --update-apply sololink --reset"
  command: "sololink_config --update-apply sololink"

- name: reboot to deploy (very slowly)
  reboot:
    reboot_timeout: 3600
