---
- name: Download {{ ArduCopter_File }}
  local_action: get_url url={{ _ArduCopter_URI }} dest="{{ tmp }}/{{ ArduCopter_File }}" force=no
  become: false
  register: result
  until: result is success
  retries: 3
  delay: 2

- name: copy to copter
  copy:
    src: "{{ tmp }}/{{ ArduCopter_File }}"
    dest: "/firmware/{{ ArduCopter_File }}"
    force: yes

- name: reboot to deploy (very slowly)
  reboot:
    reboot_timeout: 3600
