---
- name: inherit
  import_role:
    name: solo/base

- name: "Download {{ ArduCopter_File }}"
  get_url:
    url: "{{ _ArduCopter_URI }}"
    dest: "{{ tmp }}/{{ ArduCopter_File }}"
    force: no
  delegate_to: localhost
  become: false
  register: result
  until: result is success
  retries: 3
  delay: 2

- name: must have dir
  file:
    path: /firmware
    mode: 0777
    state: directory

- name: copy to copter
  copy:
    src: "{{ tmp }}/{{ ArduCopter_File }}"
    dest: "/firmware/{{ ArduCopter_File }}"
    mode: 0660
    force: yes

- name: reboot to deploy (very slowly)
  reboot:
    reboot_timeout: 3600
  tags:
    - molecule-notest
