---
- name: inherit
  import_role:
    name: solo/base

- name: "Download {{ ArduCopter_File }}"
  get_url:
    url: "{{ _ArduCopter_URI }}"
    dest: "{{ tmp }}/{{ ArduCopter_File }}"
    force: no
  delegate_to: localhost
  become: false
  register: result
  until: result is success
  retries: 3
  delay: 2

- name: must have bin dir
  file:
    path: /usr/bin
    mode: 0777
    state: directory

- name: must have firmware dir
  file:
    path: /firmware
    mode: 0777
    state: directory

- name: copy pixhawk.py
  copy:
    src: pixhawk.py
    dest: /usr/bin/pixhawk.py
    mode: 0770
    force: yes

- name: copy upgrader.py
  copy:
    src: uploader.py
    dest: /usr/bin/uploader.py
    mode: 0770
    force: yes

- name: copy {{ ArduCopter_File }}
  copy:
    src: "{{ tmp }}/{{ ArduCopter_File }}"
    dest: "/firmware/{{ ArduCopter_File }}"
    mode: 0660
    force: yes

- name: reboot to deploy (very slowly)
  reboot:
    reboot_timeout: 600
  tags:
    - molecule-notest
