---
- name: Converge
  hosts: all
  tasks:
    - name: "solo controller wifi"
      include_role:
        name: "solo/controller/wifi"
      vars:
        wifi_network_conf: |
          ssid="REGUS"
          key_mgmt=NONE

    - name: "solo copter autopilot upgrade"
      include_role:
        name: "solo/copter/autopilot"