---
- name: Converge
  hosts: all
  tasks:
    - name: "solo wifi"
      include_role:
        name: "solo/controller/wifi"
      vars:
        wifi_network_conf: |
          ssid="REGUS"
          key_mgmt=NONE