---
- hosts:
    - controller
  # roles:
  #   - solo/controller
  vars:
    wifi_network_conf: |
      ssid="REGUS"
      key_mgmt=NONE
  tasks:
    - name: "wifi"
      import_role:
        name: solo/controller
        tasks_from: wifi.yml

- hosts:
    - copter
  # roles:
  #   - solo/copter
  tasks:
    - name: "upgrade-autopilot"
      import_role:
        name: solo/copter
        tasks_from: upgrade-autopilot.yml
    - name: "upgrade-iMX"
      import_role:
        name: solo/copter
        tasks_from: upgrade-iMX.yml

- hosts:
    - controller
  # roles:
  #   - solo/controller
  tasks:
    - name: "upgrade-iMX"
      import_role:
        name: solo/controller
        tasks_from: upgrade-iMX.yml
