---
#dependency:
#  name: galaxy
driver:
  name: docker
platforms:
  - name: controller
    image: jrei/systemd-fedora:latest
    # image: crops/poky
    pre_build_image: true

  - name: copter
    image: jrei/systemd-fedora:latest
    # image: crops/poky
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
