---
- name: import vars
  import_role:
    name: solo/base

- name: Download {{ iMX_file }}
  block:
    - name: Download {{ _iMX_tar }}
      get_url:
        url: "{{ _iMX_tar_URI }}"
        dest: "{{ tmp }}/{{ _iMX_tar }}"
        force: no
      delegate_to: localhost
      become: false
      register: result
      until: result is success
      retries: 3
      delay: 2 ## TODO: merge with below

    - name: Download {{ _iMX_md5 }}
      get_url:
        url: "{{ _iMX_md5_URI }}"
        dest: "{{ tmp }}/{{ _iMX_md5 }}"
        force: no
      delegate_to: localhost
      become: false
      register: result
      until: result is success
      retries: 3
      delay: 2

- name: must have dir
  file:
    path: /log/updates
    mode: 0777
    state: directory

- name: update-prepare
  command: "sololink_config --update-prepare sololink"

## TODO: manually start controller

- name: Wait for reboot
  wait_for_connection:
    delay: 15
    timeout: 600

- name: copy {{ iMX_file }}
  block:
    - name: copy tar
      copy:
        src: "{{ tmp }}/{{ _iMX_tar }}"
        dest: "/log/updates/{{ _iMX_tar }}"
        mode: 0660
        force: yes

    - name: copy md5
      copy:
        src: "{{ tmp }}/{{ _iMX_md5 }}"
        dest: "/log/updates/{{ _iMX_md5 }}"
        mode: 0660
        force: yes

- name: update-apply
  # command: "sololink_config --update-apply sololink --reset"
  command: "sololink_config --update-apply sololink --reset"
## TODO: manually start controller

# - name: reboot to deploy (very slowly)
#   reboot:
#     reboot_timeout: 3600
#   tags:
#     - molecule-notest
