---
name: CI

on:
  push

jobs:
  check-syntax:
    runs-on: ubuntu-20.04
    name: check-syntax
    container:
      image: diodonfrost/ansible-fedora:34
      env:
        container: docker
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
        - ${{ github.workspace }}:/etc/ansible/roles/ansible-role-openvpn
      options: "--cap-add NET_ADMIN --cap-add SYS_ADMIN --device /dev/net/tun"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check syntax of ansible playbook
        run: ansible-playbook /etc/ansible/roles/ansible-role-openvpn/tests/test.yml --syntax-check

  build-fedora:
    runs-on: ubuntu-20.04
    name: fedora-34
#    needs:
#      - check-syntax
#    strategy:
#      fail-fast: false
#      matrix:
#        version:
#          - "32"
#          - "33"
#          - "34"

    container:
      image: diodonfrost/ansible-fedora:34
      env:
        container: docker
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
        - ${{ github.workspace }}:/etc/ansible/roles/ansible-role-openvpn
      options: "--cap-add NET_ADMIN --cap-add SYS_ADMIN --device /dev/net/tun"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Make sure ansible connection is sane
        run: ansible -m setup -c local -i 127.0.0.1, all
      - name: Run ansible playbook
        run: ansible-playbook /etc/ansible/roles/ansible-role-openvpn/tests/test.yml -vv
      - name: Check idempotency
        run: ansible-playbook /etc/ansible/roles/ansible-role-openvpn/tests/test.yml -vv
      - name: Container state debug output
        continue-on-error: true
        run: |
          ls -lR /etc/openvpn
          echo "cat /etc/openvpn/**/openvpn_udp_1194.conf"
          cat /etc/openvpn/**/openvpn_udp_1194.conf
          echo "cat /etc/openvpn/**/alpha-*.ovpn"
          cat /etc/openvpn/**/alpha-*.ovpn
